#!/usr/bin/env python3
"""Parse training_plan.html and generate TrainingPlanData.swift.

Usage: python3 Scripts/generate_plan_data.py <path-to-training_plan.html>
Writes WorkoutTracker/Sources/TrainingPlanData.swift.
"""
import html
import re
import sys

MONTHS = {m: i + 1 for i, m in enumerate(
    ["January", "February", "March", "April", "May", "June", "July",
     "August", "September", "October", "November", "December"])}

WEEK_RE = re.compile(
    r'<h2 class="wk">Week (\d+) <span class="sub">Cycle (\d+), week (\d+) of 4'
    r'( &middot; DELOAD WEEK)?</span></h2>')
CARD_RE = re.compile(
    r'<div class="card( dl)?">\s*'
    r'<div class="hd"><span class="dt">([^<]+)</span><span class="lb">([^<]+)</span></div>\s*'
    r'<table>(.*?)</table>', re.S)
ROW_RE = re.compile(r'<tr( class="skip")?>(.*?)</tr>', re.S)
TD_RE = re.compile(
    r'<td class="ex">(.*?)</td><td class="sr">(.*?)</td>'
    r'<td class="w">(.*?)</td><td class="n">(.*?)</td>', re.S)
LIFT_RE = re.compile(r'data-lift="(\w+)" data-cycle="(\d+)" data-pct="(\d+)"')


def clean(s):
    return " ".join(html.unescape(s).split())


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    src = open(sys.argv[1]).read()

    # Map each card position to its enclosing week header.
    weeks = [(m.start(), int(m.group(1)), int(m.group(2)), int(m.group(3)),
              m.group(4) is not None) for m in WEEK_RE.finditer(src)]

    days = []
    for m in CARD_RE.finditer(src):
        wk = [w for w in weeks if w[0] < m.start()][-1]
        _, week, cycle, week_of_cycle, deload = wk
        date_txt = clean(m.group(2))          # "Monday, August 17"
        weekday, month_day = date_txt.split(", ")
        month_name, day_num = month_day.rsplit(" ", 1)
        entries = []
        for rm in ROW_RE.finditer(m.group(4)):
            skipped = rm.group(1) is not None
            td = TD_RE.search(rm.group(2))
            ex, sr, w, note = (clean(td.group(i)) for i in range(1, 5))
            lift = LIFT_RE.search(rm.group(2))
            if lift:
                weight = (f'.percent(lift: .{lift.group(1)}, '
                          f'cycle: {lift.group(2)}, pct: {lift.group(3)})')
            else:
                weight = ".none"
            entries.append(
                f'            PlanEntry(exercise: {swift_str(ex)}, '
                f'setsReps: {swift_str(sr)}, weight: {weight}, '
                f'note: {swift_str(note)}, isSkipped: {str(skipped).lower()})')
        days.append((weekday, MONTHS[month_name], int(day_num), week, cycle,
                     week_of_cycle, clean(m.group(3)), deload, entries))

    out = ["// Generated by Scripts/generate_plan_data.py — do not edit by hand.",
           "", "enum TrainingPlanData {", "    static let days: [PlanDay] = ["]
    for i, (weekday, month, day, week, cycle, woc, label, deload, entries) in enumerate(days):
        out.append(f'        PlanDay(id: {i}, weekday: "{weekday}", '
                   f'month: {month}, day: {day}, week: {week}, cycle: {cycle}, '
                   f'weekOfCycle: {woc}, label: "{label}", '
                   f'isDeload: {str(deload).lower()}, entries: [')
        out.extend(e + "," for e in entries)
        out.append("        ]),")
    out += ["    ]", "}", ""]

    dest = "WorkoutTracker/Sources/TrainingPlanData.swift"
    open(dest, "w").write("\n".join(out))
    print(f"{len(days)} days -> {dest}")


if __name__ == "__main__":
    main()
